### ISSUE TITLE
nightly version problem..

### ISSUE THREAD

**Issue by JoanTheSpark** [HiGregSmith/KiPadCheck#1]
I get this error when I start the script in a nightly version of KiCAD under Windows 7-64bit:

>Startup script executed: C:\Users\...\AppData\Roaming\kicad\PyShell_pcbnew_startup.py
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\..\AppData\Roaming\kicad\PyShell_pcbnew_startup.py", line 9, in <module>
    import kipadcheck
  File "C:\Program Files\KiCad\share\kicad\scripting\plugins/kipadcheck.py", line 680, in <module>
    class KiPadCheck( pcbnew.ActionPlugin ):
  File "C:\Program Files\KiCad\share\kicad\scripting\plugins/kipadcheck.py", line 1451, in KiPadCheck
    pcbnew.BLACK: 'BLACK',
AttributeError: 'module' object has no attribute 'BLACK'

KiCAD version info

> Application: kicad
Version: (2017-05-12 revision b823d0b78)-makepkg, release build
Libraries: wxWidgets 3.0.2
           libcurl/7.52.1 OpenSSL/1.0.2k zlib/1.2.11 libssh2/1.8.0 nghttp2/1.19.0 librtmp/2.3
Platform: Windows 7 (build 7601, Service Pack 1), 64-bit edition, 64 bit, Little endian, wxMSW Build Info
wxWidgets: 3.0.2 (wchar_t,wx containers,compatible with 2.8)
Boost: 1.60.0
Curl: 7.52.1
KiCad - Compiler: GCC 6.3.0 with C++ ABI 1010
        Settings: USE_WX_GRAPHICS_CONTEXT=OFF
                  USE_WX_OVERLAY=OFF
                  KICAD_SCRIPTING=ON
                  KICAD_SCRIPTING_MODULES=ON
                  KICAD_SCRIPTING_WXPYTHON=ON
                  KICAD_SCRIPTING_ACTION_MENU=ON
                  BUILD_GITHUB_PLUGIN=ON
                  KICAD_USE_OCE=ON

**Comment by HiGregSmith** [comment]
Attempted fix in d4b547e
Current master contains the fix. 

Within github, the previous file was inadvertently deleted. I'm still learning how github works!

**Comment by JoanTheSpark** [comment]
It loads now - kudos, but nothing happens when I click on the KiPadCheck entry in the Tools menu.

There is no warning/error/etc. anywhere to be found afaik.

Is there anything I can do in the console to 'provoke' a reaction from the script?

**Comment by HiGregSmith** [comment]
Yes.
Type "kipadcheck.kpc.MenuItemPadInfo(None)"
Please post the error messages it displays in the console.

**Comment by HiGregSmith** [comment]
You can also check the text window in the main KiCad window (where pcbnew, eeschema, gerberview, etc are launched).

It should report:
    Starting MenuItemPadInfo()...
    Finished MenuItemPadInfo()

**Comment by JoanTheSpark** [comment]
python shell:
> \>kipadcheck.kpc.MenuItemPadInfo(None)
> Traceback (most recent call last):
>   File "<input>", line 1, in <module>
>   File "C:\Program Files\KiCad\share\kicad\scripting\plugins/kipadcheck.py", line 1448, in MenuItemPadInfo
>     range(pcbnew.LAYER_ID_COUNT))
> AttributeError: 'module' object has no attribute 'LAYER_ID_COUNT'
> 

KiCAD main window console
> Starting Run()...
> Finished Run()
> Starting MenuItemPadInfo()...

**Comment by HiGregSmith** [comment]
interesting they dropped support for LAYER_ID_COUNT.

I hope you don't mind the repeated attempts at converting to nightlies.  THANK YOU!!

What is returned in the console with the following commands:
pcbnew.PCB_LAYER_ID
len(pcbnew.PCB_LAYER_ID)

**Comment by JoanTheSpark** [comment]
not at all .. python shell:
> \>import pcbnew
> \>pcbnew.PCB_LAYER_ID
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: 'module' object has no attribute 'PCB_LAYER_ID'
> \>len(pcbnew.PCB_LAYER_ID)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: 'module' object has no attribute 'PCB_LAYER_ID'

**Comment by HiGregSmith** [comment]
How about the following code
I had to enter line by line to get the console to recognize the indent after the while loop

    num = 0
    while (0 <= pcbnew.GetBoard().GetLayerID(pcbnew.GetBoard().GetLayerName(num)) <= 254):
        num += 1
    num

**Comment by HiGregSmith** [comment]
Someone on forums noted that PCB_LAYER_ID_COUNT does exist, so I'll try this:

    try:
        LAYERCOUNT = pcbnew.PCB_LAYER_ID_COUNT # nightlies, post 4.0.6
    except:
        LAYERCOUNT = pcbnew.LAYER_ID_COUNT # KiCad 4.0.6 stable

**Comment by HiGregSmith** [comment]
The latest KiPadCheck version includes the layer count fix. Let me know if there are other problems!

**Comment by JoanTheSpark** [comment]
Seems to run now :-)

A lot of lines in the KiCAD main window do appear.

Kudos!

**Comment by HiGregSmith** [comment]
Thank you for your help!!

Try in the Scripting Console *when the dialog is showing*:
kipadcheck.kpc.DrillInfo(None)

and

kipadcheck.kpc.SilkInfo(None)

After each command are there any error messages in the scripting console?

**Comment by JoanTheSpark** [comment]
Roger that, here you go:

> \>kipadcheck.kpc.DrillInfo(None)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\KiCad\share\kicad\scripting\plugins/kipadcheck.py", line 2328, in DrillInfo
    for t in self._board.GetTracks():
AttributeError: 'NoneType' object has no attribute 'GetTracks'
> \>kipadcheck.kpc.SilkInfo(None)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\KiCad\share\kicad\scripting\plugins/kipadcheck.py", line 1971, in SilkInfo
    pads = self.GetPads()
  File "C:\Program Files\KiCad\share\kicad\scripting\plugins/kipadcheck.py", line 1510, in GetPads
    return [self._board.GetPad(n) for n in range(self._board.GetPadCount())]
AttributeError: 'NoneType' object has no attribute 'GetPadCount'

PS: I hope they don't change this faster than you can get behind it though. The nightly I use is from May = 2.5 months old by now ;-)

**Comment by HiGregSmith** [comment]
SilkInfo and DrillInfo both use the progress bar and rely on wx functions.

If the Dialog was already up when you clicked the KiPadCheck menu item, then they also rely on KiCad's window names for the console window and pcbnew window.

**Comment by JoanTheSpark** [comment]
Nothing happens for the Drill button and the 'progress bar' line appears once I click on the Silk button..

![kicad_kipadcheck_1](https://user-images.githubusercontent.com/14078073/28776841-cbb70618-763b-11e7-8a42-1c61850614d3.jpg)

**Comment by HiGregSmith** [comment]
What happens when you type in
kipadcheck.kpc.MenuItemPadInfo(None)

then after that:
kipadcheck.kpc._board

Notes:
self._board is set in MenuItemPadInfo with:
self._board = pcbnew.GetBoard()

**Comment by JoanTheSpark** [comment]
> \>kipadcheck.kpc.MenuItemPadInfo(None)
> \>kipadcheck.kpc._board
<pcbnew.BOARD; proxy of <Swig Object of type 'BOARD *' at 0x0000000009a52bd0> >

**Comment by HiGregSmith** [comment]
Hmmmm... what about
kipadcheck.kpc._board.GetPadCount()

[The documentation](http://ci.kicad-pcb.org/job/kicad-doxygen/ws/build/pcbnew/doxygen-python/html/classpcbnew_1_1BOARD.html#ad2ec15fa39487a2af6bbeb14209b61be) seems to indicate GetPadCount() still exists :-(

**Comment by JoanTheSpark** [comment]
> \>kipadcheck.kpc._board.GetPadCount()
741

It does ;-)

**Comment by HiGregSmith** [comment]
Try closing the KiPadCheck window and selecting Tools > KiPadCheck again. Does that help?

If the window is not closed and you update the python file, it might not initialize correctly.

**Comment by JoanTheSpark** [comment]
Tried different things, fresh restart of KiCAD inclusive. But nothing happens when I click on the drill button and the silk button only gives the progress bar response.

**Comment by HiGregSmith** [comment]
Ok, we've tried all the first level stuff. Will have to reconvene a little later. Thanks for all your help. We'll get it solved soon, I hope.

**Comment by JoanTheSpark** [comment]
No worries, keep up the good work!

**Comment by HiGregSmith** [comment]
Thanks! The next update is ready for you to try. Instead of figuring out exactly what was going on, I eliminated the class variable '_board'.

Also, where they were not already ordered by index, the pad and drill lists are now ordered by area.

**Comment by JoanTheSpark** [comment]
Same as before, Drill nothing and Silk just gives progress blabla ;-)

**Comment by HiGregSmith** [comment]
What is the error in scripting console?

kipadcheck.kpc.DrillInfo(None)
(Make sure to do this with the dialog showing.)

**Comment by HiGregSmith** [comment]
Also, try this in the scripting console:

Close the dialog.

    reload kipadcheck
    kipadcheck.Run()
    kipadcheck.kpc.MenuItemPadInfo(None)
    kipadcheck.kpc.DrillInfo(None)

**Comment by JoanTheSpark** [comment]
> \>kipadcheck.kpc.DrillInfo(None)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\KiCad\share\kicad\scripting\plugins/kipadcheck.py", line 2376, in DrillInfo
    self._vias = self.get_vias()
  File "C:\Program Files\KiCad\share\kicad\scripting\plugins/kipadcheck.py", line 1502, in get_vias
    return filter((lambda x: x.Cast_to_VIA()), pcbnew.GetBoard().GetTracks())
  File "C:\Program Files\KiCad\share\kicad\scripting\plugins/kipadcheck.py", line 1502, in <lambda>
    return filter((lambda x: x.Cast_to_VIA()), pcbnew.GetBoard().GetTracks())
  File "C:\Program Files\KiCad\lib\python2.7\site-packages/pcbnew.py", line 11437, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, TRACK, name)
  File "C:\Program Files\KiCad\lib\python2.7\site-packages/pcbnew.py", line 74, in _swig_getattr
    return _swig_getattr_nondynamic(self, class_type, name, 0)
  File "C:\Program Files\KiCad\lib\python2.7\site-packages/pcbnew.py", line 69, in _swig_getattr_nondynamic
    return object.__getattr__(self, name)
AttributeError: type object 'object' has no attribute '__getattr__'

> \>reload kipadcheck
<module 'kipadcheck' from 'C:\Program Files\KiCad\share\kicad\scripting\plugins/kipadcheck.py'>
> \>kipadcheck.Run()
> \>kipadcheck.kpc.MenuItemPadInfo(None)
> \>kipadcheck.kpc.DrillInfo(None)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\KiCad\share\kicad\scripting\plugins/kipadcheck.py", line 2376, in DrillInfo
    self._vias = self.get_vias()
  File "C:\Program Files\KiCad\share\kicad\scripting\plugins/kipadcheck.py", line 1502, in get_vias
    return filter((lambda x: x.Cast_to_VIA()), pcbnew.GetBoard().GetTracks())
  File "C:\Program Files\KiCad\share\kicad\scripting\plugins/kipadcheck.py", line 1502, in <lambda>
    return filter((lambda x: x.Cast_to_VIA()), pcbnew.GetBoard().GetTracks())
  File "C:\Program Files\KiCad\lib\python2.7\site-packages/pcbnew.py", line 11437, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, TRACK, name)
  File "C:\Program Files\KiCad\lib\python2.7\site-packages/pcbnew.py", line 74, in _swig_getattr
    return _swig_getattr_nondynamic(self, class_type, name, 0)
  File "C:\Program Files\KiCad\lib\python2.7\site-packages/pcbnew.py", line 69, in _swig_getattr_nondynamic
    return object.__getattr__(self, name)
AttributeError: type object 'object' has no attribute '__getattr__'

**Comment by HiGregSmith** [comment]
Try:
https://github.com/HiGregSmith/KiPadCheck/blob/nightly_4.0.6/kipadcheck.py
If you're running OpenGL, be sure after drill or silk to switch views to default and back so you can see the newly selected items (the errors). F9 then F11 works for me.

**Comment by HiGregSmith** [comment]
There's still a problem with the rotation of text and pads. The method is different with the nightly. Also, you may not be able to set Outline_Thickness to anything but 0. Continuing to debug.

**Comment by HiGregSmith** [comment]
[Text rotation fixed](https://github.com/HiGregSmith/KiPadCheck/blob/nightly_4.0.6/kipadcheck.py) on nightly build (July 31, 2017).

**Comment by JoanTheSpark** [comment]
Now you've got it :-)
Works.

**Comment by HiGregSmith** [comment]
Awesome! Thank you!
