### ISSUE TITLE
GUI components not viewable

### ISSUE THREAD

**Issue by aurabindo** [HiGregSmith/KiPadCheck#2]
I built KiCad from sources, and I only see the following when invoking the script from Pcbnew:

![gui_issues](https://user-images.githubusercontent.com/1412512/28959522-66992fb0-7918-11e7-95e4-73c7f806888d.png)

It is KiPadCheck from master branch. I am on Linux.

**Comment by HiGregSmith** [comment]
I added some window sizing calls in the panel and frame wx components. Try the latest nightly commit and let me know how it works. The image above was invaluable in demonstrating the problem. Unfortunately, I don't have a Linux installation to test.

**Comment by aurabindo** [comment]
Sadly it still did not fix the issue:
![nightly](https://user-images.githubusercontent.com/1412512/28993645-3a2aa514-79d9-11e7-9eee-f7d34f976ed3.png)

**Comment by aurabindo** [comment]
Made a pull request #3 , but please verify it on your machine since I do not have access to windows.

Now it looks likes below:

![kipad_4](https://user-images.githubusercontent.com/1412512/28994287-10e29f0e-79e8-11e7-9959-2329f97af168.png)
